name: Publish
on: [workflow_dispatch] # Manual trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: eclipse-temurin:20-jdk
      options: --user root
    steps:
      - run: apt update && apt install git -y && git --version
      - run: git config --global --add safe.directory /__w/Blockus/Blockus
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: FabricMC/fabric-action-scripts@v2
        id: changelog
        with:
          context: changelog
          workflow_id: publish.yml
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build publish publishMods --stacktrace -Porg.gradle.parallel.threads=4
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
